export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCAR_PRODUCTOS = 'COMENZAR_DESCAR_PRODUCTOS';
export const DERCARGA_PRODUCTOS_EXITO = 'DERCARGA_PRODUCTOS_EXITO';
export const DERCARGA_PRODUCTOS_ERROR = 'DERCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const PRODUCTO_EDITAR_EXITO = 'PRODUCTO_EDITAR_EXITO';
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';

export const OCULTAR_ALERTA = 'PRODUCTO_EDITAR_ERROR';
export const MOSTRAR_ALERTA = 'PRODUCTO_EDITAR_ERROR';